"""
DASTCOM5 Query Tool
===================

:Authors:
1) Antonio Hidalgo (antoniohidalgo.inves@gmail.com)
2) Juan Luis Cano Rodríguez (juanlu001@gmail.com)

This module contains various methods for querying the
DASTCOM5.

All of the methods are coded as part of SOCIS 2017 for poliastro by Antonio Hidalgo[1].
"""
from astropy import config as _config


class Conf(_config.ConfigNamespace):
    AST_DTYPE = np.dtype(
        [
            ("NO", np.int32),
            ("NOBS", np.int32),
            ("OBSFRST", np.int32),
            ("OBSLAST", np.int32),
            ("EPOCH", np.float64),
            ("CALEPO", np.float64),
            ("MA", np.float64),
            ("W", np.float64),
            ("OM", np.float64),
            ("IN", np.float64),
            ("EC", np.float64),
            ("A", np.float64),
            ("QR", np.float64),
            ("TP", np.float64),
            ("TPCAL", np.float64),
            ("TPFRAC", np.float64),
            ("SOLDAT", np.float64),
            ("SRC1", np.float64),
            ("SRC2", np.float64),
            ("SRC3", np.float64),
            ("SRC4", np.float64),
            ("SRC5", np.float64),
            ("SRC6", np.float64),
            ("SRC7", np.float64),
            ("SRC8", np.float64),
            ("SRC9", np.float64),
            ("SRC10", np.float64),
            ("SRC11", np.float64),
            ("SRC12", np.float64),
            ("SRC13", np.float64),
            ("SRC14", np.float64),
            ("SRC15", np.float64),
            ("SRC16", np.float64),
            ("SRC17", np.float64),
            ("SRC18", np.float64),
            ("SRC19", np.float64),
            ("SRC20", np.float64),
            ("SRC21", np.float64),
            ("SRC22", np.float64),
            ("SRC23", np.float64),
            ("SRC24", np.float64),
            ("SRC25", np.float64),
            ("SRC26", np.float64),
            ("SRC27", np.float64),
            ("SRC28", np.float64),
            ("SRC29", np.float64),
            ("SRC30", np.float64),
            ("SRC31", np.float64),
            ("SRC32", np.float64),
            ("SRC33", np.float64),
            ("SRC34", np.float64),
            ("SRC35", np.float64),
            ("SRC36", np.float64),
            ("SRC37", np.float64),
            ("SRC38", np.float64),
            ("SRC39", np.float64),
            ("SRC40", np.float64),
            ("SRC41", np.float64),
            ("SRC42", np.float64),
            ("SRC43", np.float64),
            ("SRC44", np.float64),
            ("SRC45", np.float64),
            ("PRELTV", np.int8),
            ("SPHMX3", np.int8),
            ("SPHMX5", np.int8),
            ("JGSEP", np.int8),
            ("TWOBOD", np.int8),
            ("NSATS", np.int8),
            ("UPARM", np.int8),
            ("LSRC", np.int8),
            ("NDEL", np.int16),
            ("NDOP", np.int16),
            ("H", np.float32),
            ("G", np.float32),
            ("A1", np.float32),
            ("A2", np.float32),
            ("A3", np.float32),
            ("R0", np.float32),
            ("ALN", np.float32),
            ("NM", np.float32),
            ("NN", np.float32),
            ("NK", np.float32),
            ("LGK", np.float32),
            ("RHO", np.float32),
            ("AMRAT", np.float32),
            ("ALF", np.float32),
            ("DEL", np.float32),
            ("SPHLM3", np.float32),
            ("SPHLM5", np.float32),
            ("RP", np.float32),
            ("GM", np.float32),
            ("RAD", np.float32),
            ("EXTNT1", np.float32),
            ("EXTNT2", np.float32),
            ("EXTNT3", np.float32),
            ("MOID", np.float32),
            ("ALBEDO", np.float32),
            ("BVCI", np.float32),
            ("UBCI", np.float32),
            ("IRCI", np.float32),
            ("RMSW", np.float32),
            ("RMSU", np.float32),
            ("RMSN", np.float32),
            ("RMSNT", np.float32),
            ("RMSH", np.float32),
            ("EQUNOX", "|S4"),
            ("PENAM", "|S6"),
            ("SBNAM", "|S12"),
            ("SPTYPT", "|S5"),
            ("SPTYPS", "|S5"),
            ("DARC", "|S9"),
            ("COMNT1", "|S41"),
            ("COMNT2", "|S80"),
            ("DESIG", "|S13"),
            ("ASTEST", "|S8"),
            ("IREF", "|S10"),
            ("ASTNAM", "|S18"),
        ]
    )

    COM_DTYPE = np.dtype(
        [
            ("NO", np.int32),
            ("NOBS", np.int32),
            ("OBSFRST", np.int32),
            ("OBSLAST", np.int32),
            ("EPOCH", np.float64),
            ("CALEPO", np.float64),
            ("MA", np.float64),
            ("W", np.float64),
            ("OM", np.float64),
            ("IN", np.float64),
            ("EC", np.float64),
            ("A", np.float64),
            ("QR", np.float64),
            ("TP", np.float64),
            ("TPCAL", np.float64),
            ("TPFRAC", np.float64),
            ("SOLDAT", np.float64),
            ("SRC1", np.float64),
            ("SRC2", np.float64),
            ("SRC3", np.float64),
            ("SRC4", np.float64),
            ("SRC5", np.float64),
            ("SRC6", np.float64),
            ("SRC7", np.float64),
            ("SRC8", np.float64),
            ("SRC9", np.float64),
            ("SRC10", np.float64),
            ("SRC11", np.float64),
            ("SRC12", np.float64),
            ("SRC13", np.float64),
            ("SRC14", np.float64),
            ("SRC15", np.float64),
            ("SRC16", np.float64),
            ("SRC17", np.float64),
            ("SRC18", np.float64),
            ("SRC19", np.float64),
            ("SRC20", np.float64),
            ("SRC21", np.float64),
            ("SRC22", np.float64),
            ("SRC23", np.float64),
            ("SRC24", np.float64),
            ("SRC25", np.float64),
            ("SRC26", np.float64),
            ("SRC27", np.float64),
            ("SRC28", np.float64),
            ("SRC29", np.float64),
            ("SRC30", np.float64),
            ("SRC31", np.float64),
            ("SRC32", np.float64),
            ("SRC33", np.float64),
            ("SRC34", np.float64),
            ("SRC35", np.float64),
            ("SRC36", np.float64),
            ("SRC37", np.float64),
            ("SRC38", np.float64),
            ("SRC39", np.float64),
            ("SRC40", np.float64),
            ("SRC41", np.float64),
            ("SRC42", np.float64),
            ("SRC43", np.float64),
            ("SRC44", np.float64),
            ("SRC45", np.float64),
            ("SRC46", np.float64),
            ("SRC47", np.float64),
            ("SRC48", np.float64),
            ("SRC49", np.float64),
            ("SRC50", np.float64),
            ("SRC51", np.float64),
            ("SRC52", np.float64),
            ("SRC53", np.float64),
            ("SRC54", np.float64),
            ("SRC55", np.float64),
            ("PRELTV", np.int8),
            ("SPHMX3", np.int8),
            ("SPHMX5", np.int8),
            ("JGSEP", np.int8),
            ("TWOBOD", np.int8),
            ("NSATS", np.int8),
            ("UPARM", np.int8),
            ("LSRC", np.int8),
            ("IPYR", np.int16),
            ("NDEL", np.int16),
            ("NDOP", np.int16),
            ("NOBSMT", np.int16),
            ("NOBSMN", np.int16),
            ("H", np.float32),
            ("G", np.float32),
            ("M1 (MT)", np.float32),
            ("M2 (MN)", np.float32),
            ("K1 (MTSMT)", np.float32),
            ("K2 (MNSMT)", np.float32),
            ("PHCOF (MNP)", np.float32),
            ("A1", np.float32),
            ("A2", np.float32),
            ("A3", np.float32),
            ("DT", np.float32),
            ("R0", np.float32),
            ("ALN", np.float32),
            ("NM", np.float32),
            ("NN", np.float32),
            ("NK", np.float32),
            ("S0", np.float32),
            ("TCL", np.float32),
            ("RHO", np.float32),
            ("AMRAT", np.float32),
            ("AJ1", np.float32),
            ("AJ2", np.float32),
            ("ET1", np.float32),
            ("ET2", np.float32),
            ("DTH", np.float32),
            ("ALF", np.float32),
            ("DEL", np.float32),
            ("SPHLM3", np.float32),
            ("SPHLM5", np.float32),
            ("RP", np.float32),
            ("GM", np.float32),
            ("RAD", np.float32),
            ("EXTNT1", np.float32),
            ("EXTNT2", np.float32),
            ("EXTNT3", np.float32),
            ("MOID", np.float32),
            ("ALBEDO", np.float32),
            ("RMSW", np.float32),
            ("RMSU", np.float32),
            ("RMSN", np.float32),
            ("RMSNT", np.float32),
            ("RMSMT", np.float32),
            ("RMSMN", np.float32),
            ("EQUNOX", "|S4"),
            ("PENAM", "|S6"),
            ("SBNAM", "|S12"),
            ("DARC", "|S9"),
            ("COMNT3", "|S49"),
            ("COMNT2", "|S80"),
            ("DESIG", "|S13"),
            ("COMEST", "|S14"),
            ("IREF", "|S10"),
            ("COMNAM", "|S29"),
        ]
    )
    ASTROQUERY_LOCAL_PATH = os.path.join(os.path.expanduser("~"), ".astroquery")
    DBS_LOCAL_PATH = os.path.join(ASTROQUERY_LOCAL_PATH, "dastcom5", "dat")
    AST_DB_PATH = os.path.join(DBS_LOCAL_PATH, "dast5_le.dat")
    COM_DB_PATH = os.path.join(DBS_LOCAL_PATH, "dcom5_le.dat")
    FTP_DB_URL = "ftp://ssd.jpl.nasa.gov/pub/ssd/"


conf = Conf()

from .core import *

__all__ = [Dastcom5, Dastcom5Class]
