name: Milestone -- Add latest if missing on merge

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'

jobs:
  milestone_pr:
    name: attach missing milestone to PR
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: scientific-python/attach-next-milestone-action@bc07be829f693829263e57d5e8489f4e57d3d420
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
